export const SET_THEME = 'SET_THEME';
export type SET_THEME_TYPE = typeof SET_THEME;

export const SET_OPEN_INSTRUCTIONS = 'SET_OPEN_INSTRUCTIONS';
export type SET_OPEN_INSTRUCTIONS_TYPE = typeof SET_OPEN_INSTRUCTIONS;

export const SET_OPEN_SCORE = 'SET_OPEN_SCORE';
export type SET_OPEN_SCORE_TYPE = typeof SET_OPEN_SCORE;

export const SET_WORD = 'SET_WORD';
export type SET_WORD_TYPE = typeof SET_WORD;

export const SET_TYPING_WORD = 'SET_TYPING_WORD';
export type SET_TYPING_WORD_TYPE = typeof SET_TYPING_WORD;

export const CLEAR_TYPED_WORD = 'CLEAR_TYPED_WORD';
export type CLEAR_TYPED_WORD_TYPE = typeof CLEAR_TYPED_WORD;

export const CLEAR_TYPED_LETTER = 'CLEAR_TYPED_LETTER';
export type CLEAR_TYPED_LETTER_TYPE = typeof CLEAR_TYPED_LETTER;
