export const SET_THEME = 'SET_THEME';
export type SET_THEME_TYPE = typeof SET_THEME;

export const SET_OPEN_INSTRUCTIONS = 'SET_OPEN_INSTRUCTIONS';
export type SET_OPEN_INSTRUCTIONS_TYPE = typeof SET_OPEN_INSTRUCTIONS;

export const SET_OPEN_SCORE = 'SET_OPEN_SCORE';
export type SET_OPEN_SCORE_TYPE = typeof SET_OPEN_SCORE;
